# -*- coding: utf-8 -*-
"""BankTurnover.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11lH_KFGfKd3XnCKMXeUoxaSgmgaZmcy9
"""

# --- Import seluruh pustaka yang dibutuhkan di awal ---
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Dense, Dropout, Conv1D, MaxPooling1D, Flatten,
    Bidirectional, LSTM
)

# Reproducibility: menetapkan random seed agar hasil eksperimen konsisten
SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)

CSV_PATH = "Churn_Modelling.csv"  # Sesuaikan path jika file disimpan di folder lain

# =====================================================================================
# SECTION 1: INPUT (PEMUATAN DATASET)
# =====================================================================================
print("=" * 80)
print("SECTION 1: INPUT (PEMUATAN DATASET)")
print("=" * 80)

# 1.1 Memuat dataset menggunakan pandas
df = pd.read_csv(CSV_PATH)

# 1.2 Menampilkan 5 baris pertama data untuk melihat gambaran umum dataset
print("\n5 Baris Pertama Dataset:")
print(df.head())

# 1.3 Menampilkan informasi ringkas dataset (jumlah baris, tipe data, non-null count)
print("\nInformasi Ringkas Dataset:")
df.info()

# 1.4 Menghapus kolom identitas yang tidak relevan untuk pemodelan
#     (RowNumber, CustomerId, dan Surname tidak memiliki pengaruh prediktif terhadap churn)
df = df.drop(columns=["RowNumber", "CustomerId", "Surname"])

print("\nKolom setelah penghapusan kolom identitas:")
print(df.columns.tolist())
print("\nShape dataset setelah pembersihan awal:", df.shape)


# =====================================================================================
# SECTION 2: PREPROCESSING & TRANSFORMATION
# =====================================================================================
print("\n" + "=" * 80)
print("SECTION 2: PREPROCESSING & TRANSFORMATION")
print("=" * 80)

# 2.1 Pengecekan missing values pada setiap kolom
print("\nJumlah Missing Values per Kolom:")
print(df.isnull().sum())

# Jika ditemukan missing values, tangani dengan imputasi median (numerik) / modus (kategorikal).
# Dataset Churn_Modelling.csv pada umumnya sudah bersih, namun blok berikut tetap disiapkan
# sebagai antisipasi agar kode robust terhadap data yang berbeda.
if df.isnull().sum().sum() > 0:
    for col in df.columns:
        if df[col].isnull().sum() > 0:
            if df[col].dtype in [np.float64, np.int64]:
                df[col] = df[col].fillna(df[col].median())
            else:
                df[col] = df[col].fillna(df[col].mode()[0])
    print("\nMissing values telah ditangani.")
else:
    print("\nTidak ditemukan missing values pada dataset.")

# 2.2 Deteksi Outlier pada fitur numerik kontinu menggunakan metode IQR (Interquartile Range)
#     Outlier adalah nilai yang jauh menyimpang dari sebaran data mayoritas dan berpotensi
#     mengganggu proses training model.
numeric_cols_for_outlier = ["CreditScore", "Age", "Balance", "EstimatedSalary", "Tenure", "NumOfProducts"]

print("\nDeteksi Outlier (Metode IQR) pada fitur numerik:")
outlier_summary = {}
for col in numeric_cols_for_outlier:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    n_outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)].shape[0]
    outlier_summary[col] = n_outliers
    print(f"  - {col:<18}: {n_outliers} outlier "
          f"(batas normal: {lower_bound:.2f} s/d {upper_bound:.2f})")

# Visualisasi boxplot untuk melihat sebaran & outlier secara visual
fig, axes = plt.subplots(2, 3, figsize=(15, 8))
axes = axes.ravel()
for i, col in enumerate(numeric_cols_for_outlier):
    axes[i].boxplot(df[col], vert=True)
    axes[i].set_title(f"Boxplot: {col}")
plt.tight_layout()
plt.suptitle("Deteksi Outlier - Boxplot Fitur Numerik", y=1.02)
plt.show()

# Penanganan outlier: menggunakan CAPPING (winsorizing) alih-alih menghapus baris,
# agar tidak kehilangan data churn (kelas minoritas) yang justru penting untuk dipelajari model.
# Nilai di luar batas bawah/atas akan "dipangkas" mengikuti batas IQR.
for col in numeric_cols_for_outlier:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df[col] = np.clip(df[col], lower_bound, upper_bound)

print("\nOutlier telah ditangani dengan metode capping (winsorizing) berbasis IQR.")

# Catatan mengenai Windowing:
# Windowing (sliding window) digunakan untuk mengubah data DERET WAKTU (time series) menjadi
# potongan-potongan berbasis waktu. Dataset Churn_Modelling.csv bersifat TABULAR/NON-SEKUENSIAL
# (setiap baris adalah nasabah independen, bukan urutan waktu), sehingga tahap windowing
# TIDAK RELEVAN/TIDAK DITERAPKAN pada studi kasus ini. Sebagai gantinya, dilakukan reshaping
# fitur menjadi format 3D [samples, time_steps, features] pada Section 3 agar tetap kompatibel
# dengan input layer Conv1D dan LSTM.

# 2.3 One-Hot Encoding pada fitur kategorikal teks: 'Geography' dan 'Gender'
#     drop_first=True digunakan untuk menghindari dummy variable trap (multikolinearitas)
categorical_cols = ["Geography", "Gender"]
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

# Pastikan hasil one-hot encoding bertipe integer (0/1), bukan boolean
for col in df.columns:
    if df[col].dtype == bool:
        df[col] = df[col].astype(int)

print("\nKolom setelah One-Hot Encoding:")
print(df.columns.tolist())

# 2.4 Memisahkan fitur (X) dan target (y)
X = df.drop(columns=["Exited"])
y = df["Exited"].values

# 2.5 Feature Scaling pada fitur numerik kontinu menggunakan StandardScaler
#     Scaling dilakukan pada SELURUH kolom fitur (setelah encoding) karena seluruh kolom
#     kini bertipe numerik, dan Deep Learning (CNN1D & BiLSTM) sensitif terhadap skala fitur.
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("\nContoh 5 baris fitur setelah scaling:")
print(pd.DataFrame(X_scaled, columns=X.columns).head())


# =====================================================================================
# SECTION 3: DATA SPLITTING & RESHAPING
# =====================================================================================
print("\n" + "=" * 80)
print("SECTION 3: DATA SPLITTING & RESHAPING")
print("=" * 80)

# 3.1 Split data menjadi Training (80%) dan Temp (20%) terlebih dahulu
X_train, X_temp, y_train, y_temp = train_test_split(
    X_scaled, y,
    test_size=0.20,
    random_state=SEED,
    stratify=y
)

# 3.2 Split Temp (20%) menjadi Validation (10%) dan Testing (10%) --> masing-masing 50% dari Temp
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp,
    test_size=0.50,
    random_state=SEED,
    stratify=y_temp
)

print(f"\nJumlah Data Training  : {X_train.shape[0]} sampel")
print(f"Jumlah Data Validation: {X_val.shape[0]} sampel")
print(f"Jumlah Data Testing   : {X_test.shape[0]} sampel")

# Verifikasi proporsi kelas target pada setiap subset (harus relatif seimbang berkat stratify)
print("\nProporsi kelas 'Exited' pada setiap subset:")
print("Training  :", np.round(np.bincount(y_train) / len(y_train), 3))
print("Validation:", np.round(np.bincount(y_val) / len(y_val), 3))
print("Testing   :", np.round(np.bincount(y_test) / len(y_test), 3))

# 3.3 Reshaping fitur input menjadi 3 dimensi [samples, time_steps, features]
#     Untuk data tabular non-sekuensial, time_steps = jumlah fitur, features = 1
#     Ini adalah pendekatan umum agar data tabular dapat diproses oleh Conv1D/LSTM.
n_features = X_train.shape[1]

X_train_reshaped = X_train.reshape((X_train.shape[0], n_features, 1))
X_val_reshaped = X_val.reshape((X_val.shape[0], n_features, 1))
X_test_reshaped = X_test.reshape((X_test.shape[0], n_features, 1))

print("\nShape data setelah reshaping (3D):")
print("X_train_reshaped:", X_train_reshaped.shape)
print("X_val_reshaped  :", X_val_reshaped.shape)
print("X_test_reshaped :", X_test_reshaped.shape)

# Parameter bersama agar perbandingan CNN1D vs BiLSTM adil
EPOCHS = 50
BATCH_SIZE = 32


# =====================================================================================
# SECTION 4: METODE 1 (CNN 1D)
# =====================================================================================
print("\n" + "=" * 80)
print("SECTION 4: METODE 1 (CNN 1D)")
print("=" * 80)

# 4.1 Membangun arsitektur CNN 1D
cnn_model = Sequential(name="CNN1D_Churn_Model")
cnn_model.add(Conv1D(filters=64, kernel_size=3, activation="relu",
                      input_shape=(n_features, 1)))
cnn_model.add(MaxPooling1D(pool_size=2))
cnn_model.add(Conv1D(filters=32, kernel_size=3, activation="relu"))
cnn_model.add(MaxPooling1D(pool_size=2))
cnn_model.add(Flatten())
cnn_model.add(Dense(64, activation="relu"))
cnn_model.add(Dropout(0.3))
cnn_model.add(Dense(1, activation="sigmoid"))  # Output biner

cnn_model.summary()

# 4.2 Compile model
cnn_model.compile(
    loss="binary_crossentropy",
    optimizer="adam",
    metrics=["accuracy"]
)

# 4.3 Melatih model menggunakan Data Training dan Data Validation
history_cnn = cnn_model.fit(
    X_train_reshaped, y_train,
    validation_data=(X_val_reshaped, y_val),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    verbose=1
)

# 4.4 Grafik evaluasi mandiri: Model Accuracy (Train vs Validation)
plt.figure(figsize=(8, 5))
plt.plot(history_cnn.history["accuracy"], label="Train Accuracy")
plt.plot(history_cnn.history["val_accuracy"], label="Validation Accuracy")
plt.title("CNN 1D - Model Accuracy (Train vs Validation)")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.grid(True)
plt.show()

# Grafik evaluasi mandiri: Model Loss (Train vs Validation)
plt.figure(figsize=(8, 5))
plt.plot(history_cnn.history["loss"], label="Train Loss")
plt.plot(history_cnn.history["val_loss"], label="Validation Loss")
plt.title("CNN 1D - Model Loss (Train vs Validation)")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)
plt.show()

# 4.5 Prediksi pada Data Testing
y_pred_cnn_prob = cnn_model.predict(X_test_reshaped)
y_pred_cnn = (y_pred_cnn_prob > 0.5).astype(int).ravel()

# Classification Report (Akurasi, Presisi, Recall, F1-Score)
print("\nClassification Report - CNN 1D:")
print(classification_report(y_test, y_pred_cnn, target_names=["Retain (0)", "Churn (1)"]))
print("Akurasi Testing CNN 1D:", accuracy_score(y_test, y_pred_cnn))

# Confusion Matrix
cm_cnn = confusion_matrix(y_test, y_pred_cnn)

plt.figure(figsize=(5, 4))
plt.imshow(cm_cnn, cmap="Blues")
plt.title("Confusion Matrix - CNN 1D")
plt.colorbar()
tick_marks = np.arange(2)
plt.xticks(tick_marks, ["Retain (0)", "Churn (1)"])
plt.yticks(tick_marks, ["Retain (0)", "Churn (1)"])
plt.xlabel("Predicted Label")
plt.ylabel("True Label")

# Menambahkan angka pada setiap sel confusion matrix
thresh = cm_cnn.max() / 2.0
for i in range(cm_cnn.shape[0]):
    for j in range(cm_cnn.shape[1]):
        plt.text(j, i, format(cm_cnn[i, j], "d"),
                  ha="center", va="center",
                  color="white" if cm_cnn[i, j] > thresh else "black")
plt.tight_layout()
plt.show()

# 4.6 Menyimpan model CNN 1D
cnn_model.save("cnn1d_model.h5")
print("\nModel CNN 1D berhasil disimpan sebagai 'cnn1d_model.h5'")


# =====================================================================================
# SECTION 5: METODE 2 (BiLSTM)
# =====================================================================================
print("\n" + "=" * 80)
print("SECTION 5: METODE 2 (BiLSTM)")
print("=" * 80)

# 5.1 Membangun arsitektur BiLSTM
bilstm_model = Sequential(name="BiLSTM_Churn_Model")
bilstm_model.add(Bidirectional(
    LSTM(64, return_sequences=True),
    input_shape=(n_features, 1)
))
bilstm_model.add(Dropout(0.3))
bilstm_model.add(Bidirectional(LSTM(32)))
bilstm_model.add(Dropout(0.3))
bilstm_model.add(Dense(32, activation="relu"))
bilstm_model.add(Dense(1, activation="sigmoid"))  # Output biner

bilstm_model.summary()

# 5.2 Compile model dengan kondisi yang setara dengan Metode 1 (CNN 1D)
bilstm_model.compile(
    loss="binary_crossentropy",
    optimizer="adam",
    metrics=["accuracy"]
)

# 5.3 Melatih model menggunakan Data Training dan Data Validation yang sama dengan Metode 1
#     Epoch dan batch_size disamakan dengan CNN 1D agar komparasi adil
history_bilstm = bilstm_model.fit(
    X_train_reshaped, y_train,
    validation_data=(X_val_reshaped, y_val),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    verbose=1
)

# 5.4 Grafik evaluasi mandiri: Model Accuracy (Train vs Validation)
plt.figure(figsize=(8, 5))
plt.plot(history_bilstm.history["accuracy"], label="Train Accuracy")
plt.plot(history_bilstm.history["val_accuracy"], label="Validation Accuracy")
plt.title("BiLSTM - Model Accuracy (Train vs Validation)")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.grid(True)
plt.show()

# Grafik evaluasi mandiri: Model Loss (Train vs Validation)
plt.figure(figsize=(8, 5))
plt.plot(history_bilstm.history["loss"], label="Train Loss")
plt.plot(history_bilstm.history["val_loss"], label="Validation Loss")
plt.title("BiLSTM - Model Loss (Train vs Validation)")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)
plt.show()

# 5.5 Prediksi pada Data Testing
y_pred_bilstm_prob = bilstm_model.predict(X_test_reshaped)
y_pred_bilstm = (y_pred_bilstm_prob > 0.5).astype(int).ravel()

# Classification Report (Akurasi, Presisi, Recall, F1-Score)
print("\nClassification Report - BiLSTM:")
print(classification_report(y_test, y_pred_bilstm, target_names=["Retain (0)", "Churn (1)"]))
print("Akurasi Testing BiLSTM:", accuracy_score(y_test, y_pred_bilstm))

# Confusion Matrix
cm_bilstm = confusion_matrix(y_test, y_pred_bilstm)

plt.figure(figsize=(5, 4))
plt.imshow(cm_bilstm, cmap="Greens")
plt.title("Confusion Matrix - BiLSTM")
plt.colorbar()
plt.xticks(tick_marks, ["Retain (0)", "Churn (1)"])
plt.yticks(tick_marks, ["Retain (0)", "Churn (1)"])
plt.xlabel("Predicted Label")
plt.ylabel("True Label")

thresh_bilstm = cm_bilstm.max() / 2.0
for i in range(cm_bilstm.shape[0]):
    for j in range(cm_bilstm.shape[1]):
        plt.text(j, i, format(cm_bilstm[i, j], "d"),
                  ha="center", va="center",
                  color="white" if cm_bilstm[i, j] > thresh_bilstm else "black")
plt.tight_layout()
plt.show()

# 5.6 Menyimpan model BiLSTM
bilstm_model.save("bilstm_model.h5")
print("\nModel BiLSTM berhasil disimpan sebagai 'bilstm_model.h5'")


# ==============================
# PERBANDINGAN AKHIR
# ==============================
print("\n" + "=" * 80)
print("PERBANDINGAN AKURASI TESTING")
print("=" * 80)
print(f"CNN 1D  - Akurasi Testing : {accuracy_score(y_test, y_pred_cnn):.4f}")
print(f"BiLSTM  - Akurasi Testing : {accuracy_score(y_test, y_pred_bilstm):.4f}")